FROM node:20.10.0

WORKDIR /usr/src/app

COPY pnpm-lock.yaml package.json vitest.config.json ./
RUN npm install -g pnpm
RUN pnpm i

COPY ./src ./src
RUN pnpm build

EXPOSE 3000:3000
CMD ["pnpm", "vitest"]
