services:
  certbot:
    image: certbot/certbot
    command: sh -c "certbot certonly --standalone -d mischaikow.com --text --agree-tos --email mischaik@gmail.com --server https://acme-v02.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    container_name: certbot
    volumes:
      - "letsencrypt:/etc/letsencrypt"

volumes:
  letsencrypt:
    name: letsencrypt_keys
